version: '3.8'

services:
    devenv:
        image: "${devimage}"
        volumes:
            - .:/app
        ports:
            - 8080:8080
        depends_on:
            - usersdb

    usersdb:
      build:
          context: .
          dockerfile: ./hack/Dockerfile.usersdb
