name: CI
on: [push]
jobs:

  build:
    name: Build and Test

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        go: [ "1.13", "1.14" ]

    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    # TODO: add build

    - name: Test
      run: make test

  linting:
    name: Linting

    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ "1.13", "1.14" ]

    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Install Go linter
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /tmp/bin v1.29.0

    #WHY: env on actions cant load the value of another env var on its definition... I think at least =/
    - name: Lint
      run: |
        export PATH="$PATH:/tmp/bin"
        make lint
